[tool.poetry]
name = "trendboard"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
sport-activities-features = "^0.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "trendboard"
version = "0.1.0"
description = "Additions th AST-Monitor module"
readme = "README.md"
requires-python = ">=3.9"
authors = [{name = "Sebastian Pack", email = "sebastian.pack@tugraz.at"}, {name = "Sebastian GÃ¼rtl", email="sebastian.guertl@tugraz.at"}]
dependencies = []
